name: Build and Release Desktop App
# Trigger this workflow on pushes (like merges) to the main branch
on:
  push:
    branches:
      -main
permissions: { contents: write}

jobs:
  build: 
    strategy: 
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps: 
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      
      - uses: actions/setup-node@v4
        with: { node-version: '18', cache: 'npm' }
        
      - name: Install deps
        run: npm ci

      - name: Build
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            npm run build:win 
          else
            npm run build:mac
          fi
      
      - name: Upload build artifects
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifacts
          path: |
            dist/*.dmg
            dist/*.zip
            dist/*.exe
  
  release: 
    needs: build
    runs-on: ubuntu-lateset
    steps: 
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with: { path: ./dist }
      
      - name: Create / update "latest" release
        uses: softprops/action-gh-release@v2
        with: 
          tag_name: latest
          name: Latest Build
          draft: false
          prerelease: false
          files: |
            dist/**/*.dmg
            dist/**/*.zip
            dist/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
